### ISSUE TITLE
This site about accessibility can't be navigated using the keyboard.

### ISSUE THREAD

**Issue by aWidebrant** [googlecodelabs/android-accessibility#1]
When attempting to read the pages of this site using the keyboard to scroll, neither the arrow keys, nor the page up and down keys, nor the space bar can be used to scroll down the page. Instead, the keyboard can only be used to switch between pages, without being able to scroll down to read their content.

**Comment by tiembo** [comment]
Hi there - this codelab has been recently updated.  Closing out this issue as it's over a year old; please comment if you are still running into this problem.  Thank you!
