### ISSUE TITLE
Can't press the green play icon, I think because there are no configurations in the project

### ISSUE THREAD

**Issue by andrewpfunk** [googlecodelabs/android-accessibility#18]

**Comment by tiembo** [comment]
Are you opening the project using the root of the repo?  Try opening one of the directories instead.

**Comment by andrewpfunk** [comment]
I think I didn't realize that Gradle was still building, or syncing, or
whatever the heck it does. There shouldn't be this much overhead to build a
simple tutorial app. Guess I need a faster computer. Thanks!

**Comment by tiembo** [comment]
Thanks for following up!
