### ISSUE TITLE
Providing Name, Role, and State for EditText element

### ISSUE THREAD

**Issue by TechThomas** [googlecodelabs/android-accessibility#3]
The guidance in the codelab for [Content Labeling](https://codelabs.developers.google.com/codelabs/basic-android-accessibility/index.html?index=..%2F..%2Fio2016#4) is similar to guidance found elsewhere in Android SDK help content.

> Hint: It is a best practice to use android:hint instead of contentDescription on EditTexts.

For WCAG2 4.1.2 we want to be able to expose a name and a value separately through the accessibility API.  Ref: [Name, Role, Value: Understanding SC 4.1.2](https://www.w3.org/TR/UNDERSTANDING-WCAG20/ensure-compat-rsv.html)  

The issue with both `android:hint` and `android:contentDescription` is that the placeholder that serves as the name disappears after a user has begun typing a value into the edit field.  Both attributes only temporarily provide a name.  

I suggest the lab be modified to include a `TextView` with the text "Favorite Song".  This can then be associated with the `EditText` using `android:labelFor`.  This will allow the field to always supply a valid name and value to Talkback throughout the interaction.

**Comment by pweaver-google** [comment]
For all Views, the content description is sent to an accessibility service regardless of whether or not there is other text in the View.

Starting in Android O, EditText hints are always available to accessibility services. Here's the [API overview](https://developer.android.com/preview/api-overview.html).

**Comment by tiembo** [comment]
Hi there - this codelab has been recently updated.  Closing out this issue as it's over a year old; please comment if you are still running into this problem.  Thank you!
