### ISSUE TITLE
accessibilityLiveRegion issue

### ISSUE THREAD

**Issue by liamj86** [googlecodelabs/android-accessibility#6]
Hi,

I'm learning accessibility development best practices through your very good tutorial. 
Unfortunately, I am struggling with the accessibilityLiveRegion attribute: When I change a radio button state, it generates the "checked", but it scraps the "Correct/Incorrect". Thanks to the "Display speech output" function, I can see that the "Correct/Incorrect" appears briefly before "checked".
I am working on a samsung galaxy s5 that I've restored to the factory level so it's running Android version 6.0.1 and Talkback is updated to it's latest version 5.2.1.
I've tried both methods: accessibilityLiveRegion and using the ViewCompat as per the tutorial, but it makes no difference. Is there a specific configuration that I should implement? Or am I doing something wrong?

Thank you very much for your help in advance.

Liam

**Comment by karan1213** [comment]
@liamj86 Did you find any solution for this

**Comment by tiembo** [comment]
Hi there - this codelab has been recently updated.  Closing out this issue as it's over a year old; please comment if you are still running into this problem.  Thank you!
